#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Interactive setup for Telegram Claude Code Bot
# Run this once:  bash setup.sh
# It walks you through everything — no technical knowledge needed.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Colors ───────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*"; }
header()  { echo -e "\n${BOLD}── $* ──${NC}\n"; }

# ── Pre-flight checks ───────────────────────────────────────────────
header "Checking prerequisites"

MISSING=()

if ! command -v python3 &>/dev/null; then
    MISSING+=("python3")
fi

if ! command -v pip3 &>/dev/null && ! python3 -m pip --version &>/dev/null 2>&1; then
    MISSING+=("pip (python3-pip)")
fi

if ! command -v claude &>/dev/null; then
    MISSING+=("claude (Claude Code CLI)")
fi

if [ ${#MISSING[@]} -gt 0 ]; then
    error "Missing required software:"
    for m in "${MISSING[@]}"; do
        echo -e "  ${RED}x${NC} $m"
    done
    echo ""
    echo "Install the missing tools first:"
    echo "  - Python 3:   https://www.python.org/downloads/"
    echo "  - Claude CLI:  npm install -g @anthropic-ai/claude-code"
    echo ""
    exit 1
fi

success "Python 3 found: $(python3 --version)"
success "Claude CLI found: $(claude --version 2>/dev/null || echo 'installed')"

# ── Step 1: Telegram Bot Token ───────────────────────────────────────
header "Step 1 — Telegram Bot Token"

echo "You need a Telegram bot token. Here's how to get one:"
echo ""
echo "  1. Open Telegram and search for @BotFather"
echo "  2. Send /newbot"
echo "  3. Choose a name (e.g. 'My Claude Bot')"
echo "  4. Choose a username (must end in 'bot', e.g. 'my_claude_bot')"
echo "  5. BotFather will give you a token like: 123456:ABC-DEF..."
echo ""

BOT_TOKEN=""
while [ -z "$BOT_TOKEN" ]; do
    read -rp "Paste your bot token here: " BOT_TOKEN
    if [ -z "$BOT_TOKEN" ]; then
        warn "Token cannot be empty. Please try again."
    fi
done
success "Bot token saved."

# ── Step 2: Your Telegram User ID ────────────────────────────────────
header "Step 2 — Your Telegram User ID"

echo "The bot will only respond to authorized users."
echo ""
echo "To find your Telegram user ID:"
echo "  1. Open Telegram and search for @userinfobot"
echo "  2. Send it any message"
echo "  3. It will reply with your user ID (a number like 123456789)"
echo ""

USER_IDS=""
while [ -z "$USER_IDS" ]; do
    read -rp "Enter your user ID (or multiple IDs separated by commas): " USER_IDS
    if [ -z "$USER_IDS" ]; then
        warn "At least one user ID is required, otherwise the bot won't respond to anyone."
    fi
done
success "Authorized users: $USER_IDS"

# ── Step 3: Default Model ────────────────────────────────────────────
header "Step 3 — Default AI Model"

echo "Choose which Claude model to use by default:"
echo ""
echo "  sonnet  - Fast and smart (recommended for most users)"
echo "  opus    - Most capable, slower and more expensive"
echo "  haiku   - Fastest and cheapest, less capable"
echo ""

DEFAULT_MODEL=""
while true; do
    read -rp "Choose model [sonnet/opus/haiku] (press Enter for sonnet): " DEFAULT_MODEL
    DEFAULT_MODEL="${DEFAULT_MODEL:-sonnet}"
    if [[ "$DEFAULT_MODEL" =~ ^(sonnet|opus|haiku)$ ]]; then
        break
    fi
    warn "Please type 'sonnet', 'opus', or 'haiku'."
done
success "Default model: $DEFAULT_MODEL"

# ── Step 4: Optional Settings ────────────────────────────────────────
header "Step 4 — Optional Settings (press Enter to skip any)"

read -rp "Working directory for Claude (press Enter for none): " WORKING_DIR
WORKING_DIR="${WORKING_DIR:-}"

read -rp "Response timeout in seconds (press Enter for 300): " TIMEOUT
TIMEOUT="${TIMEOUT:-300}"

read -rp "Metrics port (press Enter for 9101): " METRICS_PORT
METRICS_PORT="${METRICS_PORT:-9101}"

# ── Write .env file ──────────────────────────────────────────────────
header "Writing configuration"

if [ -f .env ]; then
    cp .env ".env.backup.$(date +%s)"
    info "Backed up existing .env file."
fi

cat > .env << EOF
# Telegram Bot Configuration
# Generated by setup.sh on $(date)

TELEGRAM_BOT_TOKEN=$BOT_TOKEN
ALLOWED_USER_IDS=$USER_IDS
DEFAULT_MODEL=$DEFAULT_MODEL
CLAUDE_WORKING_DIR=$WORKING_DIR
MAX_RESPONSE_TIMEOUT=$TIMEOUT
METRICS_PORT=$METRICS_PORT
EOF

success ".env file created."

# ── Set up Python virtual environment ────────────────────────────────
header "Installing dependencies"

if [ ! -d "venv" ]; then
    info "Creating Python virtual environment..."
    python3 -m venv venv
fi

info "Installing Python packages..."
venv/bin/pip install --quiet -r requirements.txt
success "Dependencies installed."

# ── Optionally install as system service ─────────────────────────────
header "Auto-start on boot (optional)"

echo "Would you like the bot to start automatically when your server boots?"
echo "This uses systemd and requires sudo."
echo ""
read -rp "Set up auto-start? [y/N]: " INSTALL_SERVICE

if [[ "$INSTALL_SERVICE" =~ ^[Yy]$ ]]; then
    SERVICE_USER="$(whoami)"
    SERVICE_FILE="$SCRIPT_DIR/telegram-bot.service"

    # Generate a service file with correct paths
    cat > "$SERVICE_FILE" << SVCEOF
[Unit]
Description=Telegram Claude Code Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$SCRIPT_DIR
ExecStart=$SCRIPT_DIR/run.sh
Restart=always
RestartSec=5
EnvironmentFile=$SCRIPT_DIR/.env
Environment=PATH=$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=$HOME
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SVCEOF

    sudo cp "$SERVICE_FILE" /etc/systemd/system/telegram-bot.service
    sudo systemctl daemon-reload
    sudo systemctl enable --now telegram-bot.service

    success "Service installed and started!"
    echo ""
    echo "  Check status:  sudo systemctl status telegram-bot.service"
    echo "  View logs:     journalctl -u telegram-bot.service -f"
    echo "  Stop:          sudo systemctl stop telegram-bot.service"
    echo "  Restart:       sudo systemctl restart telegram-bot.service"
else
    info "Skipped. You can run the bot manually with: ./run.sh"
fi

# ── Done! ─────────────────────────────────────────────────────────────
header "Setup complete!"

echo -e "Your bot is ready. Here's what to do next:"
echo ""
echo -e "  ${BOLD}Start the bot:${NC}      ./run.sh"
echo -e "  ${BOLD}Open Telegram:${NC}      Search for your bot by its username"
echo -e "  ${BOLD}Send a message:${NC}     Say hello and start chatting!"
echo ""
echo -e "  ${BOLD}Bot commands:${NC}"
echo "    /start   — Welcome message"
echo "    /new     — Start a fresh conversation"
echo "    /model   — Switch between Claude models"
echo "    /status  — Show current session info"
echo ""
success "Happy chatting!"
